CREATE TABLE IF NOT EXISTS pet (
   id LONG AUTO_INCREMENT NOT NULL,
   name CHARACTER VARYING(100) NOT NULL,
   age SMALLINT,
   weight SMALLINT,
   length SMALLINT,
   created_at TIMESTAMP,
   created_by CHARACTER VARYING(100),
   updated_at TIMESTAMP,
   updated_by CHARACTER VARYING(100),
   version LONG,
   PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS owner (
   id LONG AUTO_INCREMENT NOT NULL,
   first_name CHARACTER VARYING(100) NOT NULL,
   last_name CHARACTER VARYING(100) NOT NULL,
   age SMALLINT,
   id_pet INTEGER ARRAY,
   created_at TIMESTAMP,
   created_by CHARACTER VARYING(100),
   updated_at TIMESTAMP,
   updated_by CHARACTER VARYING(100),
   version LONG,
   PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS audit_entity (
   id LONG AUTO_INCREMENT NOT NULL,
   entity_value CHARACTER VARYING(5000) NOT NULL,
   entity_class CHARACTER VARYING(100) NOT NULL,
   audited_on TIMESTAMP,
   PRIMARY KEY (id)
);