# .github/workflows/file.yml

name: Maven JDK11 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'
          cache: maven
      - name: Granting permissions to mvnw file
        run: chmod 755 ./mvnw

      - name: Clean with Maven
        run: ./mvnw clean
      - name: Install with Maven
        run: ./mvnw install

      - name: Archive test report
        uses: actions/upload-artifact@v3
        with:
          name: Test report
          path: build/reports/tests/test
